name: slip39
description: The dart implementation of the SLIP39 for Shamir's Secret-Sharing for Mnemonic Codes.
version: 0.1.6-dev.2
author: Pal Dorogi "ilap"<pal.dorogi@gmail.com>
homepage: https://github.com/ilap/slip39-dart

dependencies:
  pointycastle: ^1.0.1
  hex: ^0.1.2
  test: ^1.6.5

environment:
  sdk: '>=2.0.0 <3.0.0'
