name: slip39
description: The dart implementation of the SLIP39 for Shamir's Secret-Sharing for Mnemonic Codes.
version: 0.3.0
homepage: https://github.com/ilap/slip39-dart

dependencies:
  pinenacl: ^0.6.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0

environment:
  sdk: '>=3.4.0 <4.0.0'
